name: samples
version: 0.0.1
description: A sample command-line application
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: 1.15.0
  json_annotation: ^4.1.0
  analyzer: '2.1.0'
  http: 0.13.3
  rxdart: 0.27.1

dev_dependencies:
#  unittest: any
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
