workspace 'RxExample'

use_frameworks!

target 'RxExample' do
platform :ios, '13.6'
project 'RxExample'
pod 'CodableAlamofire', :git => 'https://github.com/zwvista/CodableAlamofire'
pod 'RxAlamofire', '~> 6'
pod 'RxBinding', :git => 'https://github.com/zwvista/RxBinding'
pod 'NSObject+Rx'
end
