name: flutter_weather_demo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: any
  rxdart: ^0.24.1
  rx_command: ^5.0.0

flutter:
  uses-material-design: true
